#!/usr/bin/python

import os
import argparse
from PIL import Image, ImageDraw, ImageFont
from datetime import date
from shutil import copyfile

cache_path = os.path.expanduser("~/.cache/today.txt/")
today_path = os.path.expanduser("~/Dropbox/today.txt/")

font = ImageFont.truetype("/usr/share/fonts/OTF/FiraSans-UltraLight.otf", size=30)

black = (0,0,0,0)
space_cadet = (29, 41, 81, 255)
eerie_black = (27, 27, 27, 255)

dutch_white = (243, 229, 171, 255)
cardinal_red = (196, 30, 58, 255)
crimson = (220, 20, 60, 255)
ash_grey = (178, 190, 181, 255)

background_color = eerie_black
text_color = ash_grey

def render_image(text):
    img = Image.new(mode='RGBA', size=(1,1), color=background_color)
    draw = ImageDraw.Draw(img)
    size = draw.textsize(text,font=font)
    img = img.resize(size)
    draw = ImageDraw.Draw(img)
    draw.text((0,0), text, font=font, fill=text_color)
    img.save(cache_path + "image.png")

def set_wallpaper():
    os.system("setroot --bg-color '#1B1B1B' -c " + cache_path + "image.png")

def rgba2hex(rgba_tuple):
    return('#%02x%02x%02x' % rgba_tuple[0:3])

def get_today_path():
    filename = date.today().isoformat() + ".txt"
    return(today_path + filename)

def create_file(path):
    if not os.path.exists(path):
        copyfile(cache_path + "template.txt", path)
        return(True)
    return(False)


def main():
    path = get_today_path()
    file_unset = create_file(path)

    parser = argparse.ArgumentParser()
    parser.add_argument('--edit', action='store_true')
    args = parser.parse_args()

    if args.edit:
        os.system("$EDITOR " + path)
        file_unset = False

    if file_unset:
        path = cache_path + "default.txt"

    with open(path) as f:
        text = f.read()

    render_image(text)
    set_wallpaper()

if __name__ == "__main__":
    main()
